# Generated by Django 3.2 on 2021-12-15 18:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20211214_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key_expires',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 12, 17, 18, 15, 32, 173149, tzinfo=utc), null=True),
        ),
    ]
